[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/about*"
  to = "/about"
  status = 200

[[redirects]]
  from = "/skills*"
  to = "/skills"
  status = 200

[[redirects]]
  from = "/projects*"
  to = "/projects"
  status = 200

[[redirects]]
  from = "/contact*"
  to = "/contact"
  status = 200